-- Schema inicial do cadastro de imoveis.
--
-- Substitui o `spring.jpa.hibernate.ddl-auto=update` do codigo original. As
-- restricoes de dominio (faixas geograficas, area positiva) ficam tambem no
-- banco, e nao so na Bean Validation: a API nao e o unico caminho de escrita
-- (carga em lote, correcao manual, outro servico) e o banco e o ultimo guarda.

CREATE TABLE imovel (
    id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario  varchar(120)  NOT NULL,
    municipio     varchar(120)  NOT NULL,
    uf            varchar(2)    NOT NULL,
    bairro        varchar(100)  NOT NULL,
    rua           varchar(150)  NOT NULL,
    numero        varchar(10)   NOT NULL,
    latitude      numeric(10,7) NOT NULL,
    longitude     numeric(10,7) NOT NULL,
    area_m2       numeric(12,2) NOT NULL,
    ativo         boolean       NOT NULL DEFAULT true,
    criado_em     timestamptz   NOT NULL DEFAULT now(),
    atualizado_em timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT ck_imovel_latitude  CHECK (latitude  BETWEEN -90  AND 90),
    CONSTRAINT ck_imovel_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_imovel_area      CHECK (area_m2 > 0),
    CONSTRAINT ck_imovel_uf        CHECK (uf ~ '^[A-Z]{2}$')
);

COMMENT ON TABLE  imovel IS 'Imovel georreferenciado do cadastro multifinalitario.';
COMMENT ON COLUMN imovel.latitude  IS 'Graus decimais, WGS 84 (EPSG:4326). Centro do lote.';
COMMENT ON COLUMN imovel.longitude IS 'Graus decimais, WGS 84 (EPSG:4326). Centro do lote.';
