-- Promove o proprietario de campo texto para entidade propria, SEM PERDER DADO.
--
-- Sequencia (cada passo e verificavel isoladamente):
--   1. cria a tabela proprietario;
--   2. define a regra de normalizacao usada para deduplicar;
--   3. insere os proprietarios distintos a partir dos textos existentes;
--   4. preenche a FK em imovel;
--   5. ABORTA a migration se sobrar qualquer imovel sem proprietario;
--   6. so entao remove a coluna textual antiga.
--
-- Regra de normalizacao (passo 2): recorta espacos das pontas, colapsa espacos
-- internos repetidos e passa para minusculas.
--
--   '  Maria   Aparecida  Souza ' -> 'maria aparecida souza'
--
-- O que a regra DELIBERADAMENTE nao faz: remover acentos. Unir dois
-- proprietarios distintos e um erro irreversivel (some um titular do cadastro);
-- deixar 'Jose' e 'José' como dois registros e um erro reversivel, resolvido
-- depois por uma fusao explicita e auditada. Em cadastro publico, errar para o
-- lado conservador e a escolha certa.

CREATE TABLE proprietario (
    id               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             varchar(120) NOT NULL,
    nome_normalizado varchar(120) NOT NULL,
    criado_em        timestamptz  NOT NULL DEFAULT now(),
    atualizado_em    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uk_proprietario_nome_normalizado UNIQUE (nome_normalizado),
    CONSTRAINT ck_proprietario_nome CHECK (btrim(nome) <> '')
);

COMMENT ON COLUMN proprietario.nome_normalizado IS
    'Chave de deduplicacao: btrim + colapso de espacos + lower. Mantida pela aplicacao e pela funcao webgis_normaliza_nome.';

-- Passo 2 — a regra vive no banco para que migration, constraint e aplicacao
-- usem exatamente a mesma definicao.
CREATE OR REPLACE FUNCTION webgis_normaliza_nome(p_nome text)
RETURNS text AS $$
    SELECT lower(btrim(regexp_replace(p_nome, '\s+', ' ', 'g')));
$$ LANGUAGE sql IMMUTABLE STRICT;

-- Passo 3 — um proprietario por nome normalizado distinto. DISTINCT ON com
-- ORDER BY id preserva a grafia da linha mais antiga como forma canonica.
INSERT INTO proprietario (nome, nome_normalizado)
SELECT DISTINCT ON (webgis_normaliza_nome(proprietario))
       btrim(regexp_replace(proprietario, '\s+', ' ', 'g')),
       webgis_normaliza_nome(proprietario)
FROM imovel
WHERE proprietario IS NOT NULL
  AND btrim(proprietario) <> ''
ORDER BY webgis_normaliza_nome(proprietario), id;

-- Rede de seguranca: se a base legada tiver imovel com proprietario vazio ou
-- nulo, ele nao pode ser descartado nem bloquear a migration. Ganha um titular
-- explicito "nao informado", visivel e corrigivel depois.
INSERT INTO proprietario (nome, nome_normalizado)
SELECT 'Proprietário não informado', webgis_normaliza_nome('Proprietário não informado')
WHERE EXISTS (SELECT 1 FROM imovel WHERE proprietario IS NULL OR btrim(proprietario) = '')
  AND NOT EXISTS (SELECT 1 FROM proprietario
                  WHERE nome_normalizado = webgis_normaliza_nome('Proprietário não informado'));

-- Passo 4 — preenche a FK.
ALTER TABLE imovel ADD COLUMN proprietario_id bigint;

UPDATE imovel i
SET proprietario_id = p.id
FROM proprietario p
WHERE p.nome_normalizado = webgis_normaliza_nome(i.proprietario);

UPDATE imovel
SET proprietario_id = (SELECT id FROM proprietario
                       WHERE nome_normalizado = webgis_normaliza_nome('Proprietário não informado'))
WHERE proprietario_id IS NULL;

-- Passo 5 — prova de que nada se perdeu. Se falhar, o Flyway aborta e a
-- transacao inteira volta atras: a coluna antiga continua no lugar.
DO $$
DECLARE
    v_orfaos          bigint;
    v_nomes_origem    bigint;
    v_nomes_destino   bigint;
BEGIN
    SELECT count(*) INTO v_orfaos FROM imovel WHERE proprietario_id IS NULL;
    IF v_orfaos > 0 THEN
        RAISE EXCEPTION 'Migracao abortada: % imovel(is) ficaram sem proprietario_id', v_orfaos;
    END IF;

    SELECT count(DISTINCT webgis_normaliza_nome(proprietario)) INTO v_nomes_origem
    FROM imovel WHERE proprietario IS NOT NULL AND btrim(proprietario) <> '';

    SELECT count(*) INTO v_nomes_destino
    FROM proprietario
    WHERE nome_normalizado <> webgis_normaliza_nome('Proprietário não informado')
       OR EXISTS (SELECT 1 FROM imovel
                  WHERE webgis_normaliza_nome(proprietario) = webgis_normaliza_nome('Proprietário não informado'));

    IF v_nomes_destino < v_nomes_origem THEN
        RAISE EXCEPTION 'Migracao abortada: % nomes distintos na origem, apenas % proprietarios criados',
            v_nomes_origem, v_nomes_destino;
    END IF;

    RAISE NOTICE 'Migracao de proprietarios: % nomes distintos -> % proprietarios, 0 imoveis orfaos',
        v_nomes_origem, v_nomes_destino;
END $$;

ALTER TABLE imovel ALTER COLUMN proprietario_id SET NOT NULL;

ALTER TABLE imovel
    ADD CONSTRAINT fk_imovel_proprietario
    FOREIGN KEY (proprietario_id) REFERENCES proprietario (id);

-- Passo 6 — a coluna textual so cai depois da validacao acima passar.
ALTER TABLE imovel DROP COLUMN proprietario;
